/*
 * Automatically generated by jrpcgen 1.1.1 on 11/26/15 8:57 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ch.usi.inf.ds.nfsclient.jrpcgen.nfs;
/**
 * Enumeration (collection of constants).
 */
public interface ftype {

    public static final int NFNON = 0;
    public static final int NFREG = 1;
    public static final int NFDIR = 2;
    public static final int NFBLK = 3;
    public static final int NFCHR = 4;
    public static final int NFLNK = 5;

}
// End of ftype.java
