/*
 * Automatically generated by jrpcgen 1.1.1 on 11/26/15 8:57 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ch.usi.inf.ds.nfsclient.jrpcgen.nfs;
/**
 * A collection of constants used by the "nfs" ONC/RPC program.
 */
public interface nfs {
    public static final int NFSPROC_READ_2 = 6;
    public static final int NFSPROC_RMDIR_2 = 15;
    public static final int NFSPROC_RENAME_2 = 11;
    public static final int NFS_PROGRAM = 100003;
    public static final int MAXPATHLEN = 1024;
    public static final int COOKIESIZE = 4;
    public static final int NFSPROC_SETATTR_2 = 2;
    public static final int FHSIZE = 32;
    public static final int NFSPROC_READDIR_2 = 16;
    public static final int NFSPROC_CREATE_2 = 9;
    public static final int NFSPROC_NULL_2 = 0;
    public static final int NFSPROC_LINK_2 = 12;
    public static final int NFSPROC_WRITECACHE_2 = 7;
    public static final int NFSPROC_REMOVE_2 = 10;
    public static final int NFSPROC_LOOKUP_2 = 4;
    public static final int NFSPROC_STATFS_2 = 17;
    public static final int NFSPROC_MKDIR_2 = 14;
    public static final int MAXDATA = 8192;
    public static final int NFS_VERSION = 2;
    public static final int MAXNAMLEN = 255;
    public static final int NFSPROC_GETATTR_2 = 1;
    public static final int NFSPROC_WRITE_2 = 8;
    public static final int NFSPROC_READLINK_2 = 5;
    public static final int NFSPROC_SYMLINK_2 = 13;
    public static final int NFSPROC_ROOT_2 = 3;
}
// End of nfs.java
