/*
 * Automatically generated by jrpcgen 1.1.1 on 11/26/15 8:57 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ch.usi.inf.ds.nfsclient.jrpcgen.nfs;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class writeargs implements XdrAble {
    public fhandle file;
    public int beginoffset;
    public int offset;
    public int totalcount;
    public nfsdata data;

    public writeargs() {
    }

    public writeargs(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        file.xdrEncode(xdr);
        xdr.xdrEncodeInt(beginoffset);
        xdr.xdrEncodeInt(offset);
        xdr.xdrEncodeInt(totalcount);
        data.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        file = new fhandle(xdr);
        beginoffset = xdr.xdrDecodeInt();
        offset = xdr.xdrDecodeInt();
        totalcount = xdr.xdrDecodeInt();
        data = new nfsdata(xdr);
    }

}
// End of writeargs.java
