/*
 * Automatically generated by jrpcgen 1.1.1 on 11/19/15 4:33 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ch.usi.inf.ds.nfsclient.jrpcgen.mount;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class fhandle implements XdrAble {

    public byte [] value;

    public fhandle() {
    }

    public fhandle(byte [] value) {
        this.value = value;
    }

    public fhandle(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeOpaque(value, mountprog.FHSIZE);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        value = xdr.xdrDecodeOpaque(mountprog.FHSIZE);
    }

}
// End of fhandle.java
