/*
 * Automatically generated by jrpcgen 1.1.1 on 11/19/15 4:33 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ch.usi.inf.ds.nfsclient.jrpcgen.mount;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class groups implements XdrAble {
    public name grname;
    public groups grnext;

    public groups() {
    }

    public groups(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        grname.xdrEncode(xdr);
        grnext.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        grname = new name(xdr);
        grnext = new groups(xdr);
    }

}
// End of groups.java
