/*
 * Automatically generated by jrpcgen 1.1.1 on 11/19/15 4:33 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ch.usi.inf.ds.nfsclient.jrpcgen.mount;
import org.acplt.oncrpc.*;
import java.io.IOException;

import java.net.InetAddress;

import org.acplt.oncrpc.server.*;

/**
 */
public abstract class mountprogServerStub extends OncRpcServerStub implements OncRpcDispatchable {

    public mountprogServerStub()
           throws OncRpcException, IOException {
        this(0);
    }

    public mountprogServerStub(int port)
           throws OncRpcException, IOException {
        this(null, port);
    }

    public mountprogServerStub(InetAddress bindAddr, int port)
           throws OncRpcException, IOException {
        info = new OncRpcServerTransportRegistrationInfo [] {
            new OncRpcServerTransportRegistrationInfo(mountprog.MOUNTPROG, 1),
        };
        transports = new OncRpcServerTransport [] {
            new OncRpcUdpServerTransport(this, bindAddr, port, info, 32768)
            ,
            new OncRpcTcpServerTransport(this, bindAddr, port, info, 32768)
        };
    }

    public void dispatchOncRpcCall(OncRpcCallInformation call, int program, int version, int procedure)
           throws OncRpcException, IOException {
        if ( version == 1 ) {
            switch ( procedure ) {
            case 0: {
                call.retrieveCall(XdrVoid.XDR_VOID);
                MOUNTPROC_NULL_1();
                call.reply(XdrVoid.XDR_VOID);
                break;
            }
            case 1: {
                dirpath args$ = new dirpath();
                call.retrieveCall(args$);
                fhstatus result$ = MOUNTPROC_MNT_1(args$);
                call.reply(result$);
                break;
            }
            case 2: {
                call.retrieveCall(XdrVoid.XDR_VOID);
                mountlist result$ = MOUNTPROC_DUMP_1();
                call.reply(result$);
                break;
            }
            case 3: {
                dirpath args$ = new dirpath();
                call.retrieveCall(args$);
                MOUNTPROC_UMNT_1(args$);
                call.reply(XdrVoid.XDR_VOID);
                break;
            }
            case 4: {
                call.retrieveCall(XdrVoid.XDR_VOID);
                MOUNTPROC_UMNTALL_1();
                call.reply(XdrVoid.XDR_VOID);
                break;
            }
            case 5: {
                call.retrieveCall(XdrVoid.XDR_VOID);
                exportlist result$ = MOUNTPROC_EXPORT_1();
                call.reply(result$);
                break;
            }
            default:
                call.failProcedureUnavailable();
            }
        } else {
            call.failProgramUnavailable();
        }
    }

    public abstract void MOUNTPROC_NULL_1();

    public abstract fhstatus MOUNTPROC_MNT_1(dirpath arg1);

    public abstract mountlist MOUNTPROC_DUMP_1();

    public abstract void MOUNTPROC_UMNT_1(dirpath arg1);

    public abstract void MOUNTPROC_UMNTALL_1();

    public abstract exportlist MOUNTPROC_EXPORT_1();

}
// End of mountprogServerStub.java
