/*
 * Automatically generated by jrpcgen 1.1.1 on 11/19/15 4:33 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ch.usi.inf.ds.nfsclient.jrpcgen.mount;
/**
 * A collection of constants used by the "mountprog" ONC/RPC program.
 */
public interface mountprog {
    public static final int MOUNTPROC_UMNT_1 = 3;
    public static final int FHSIZE = 32;
    public static final int MOUNTPROC_MNT_1 = 1;
    public static final int MOUNTVERS = 1;
    public static final int MOUNTPROC_UMNTALL_1 = 4;
    public static final int MNTNAMLEN = 255;
    public static final int MOUNTPROC_EXPORT_1 = 5;
    public static final int MOUNTPROC_NULL_1 = 0;
    public static final int MOUNTPROC_DUMP_1 = 2;
    public static final int MOUNTPROG = 100005;
    public static final int MNTPATHLEN = 1024;
}
// End of mountprog.java
